# Nome do projeto
spring.application.name=missaoespacial

# Conexão com o Banco de Dados H2 (Modo Arquivo)
spring.datasource.url=jdbc:h2:file:./data/missaodb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Porta do servidor
server.port=8080
